create table author (id bigint generated by default as identity, name varchar(255), primary key (id));
create table book (published_date DATE, author_id bigint, id bigint generated by default as identity, title varchar(255), primary key (id));
create table chapter (book_id bigint, id bigint generated by default as identity, content varchar(255), title varchar(255), primary key (id));
create table review (book_chapter_id bigint, id bigint generated by default as identity, reviewer_id bigint, content varchar(255), primary key (id));
create table reviewer (id bigint generated by default as identity, name varchar(255), primary key (id));
alter table if exists book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author;
alter table if exists chapter add constraint FKfxaijiug52tyrl5ifextmcfqb foreign key (book_id) references book;
alter table if exists review add constraint FKl3xh7i2b39mxej7lowkh5nh8p foreign key (book_chapter_id) references chapter;
alter table if exists review add constraint FKag25ofikrsv5sujkbnlbaud4v foreign key (reviewer_id) references reviewer;
