global:
  scrape_interval: 30s
rule_files:
  - '/etc/prometheus/monitoring_rules.yml'

scrape_configs:
  - job_name: 'sender'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['sender:8081']
  - job_name: 'recipient'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'recipient:8082' ]
  - job_name: 'collector'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'collector:8083' ]
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'rabbitmq:15692' ]
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'kubernetes-nodes-cadvisor'
    scrape_interval: 10s
    scrape_timeout: 10s
    kubernetes_sd_configs:
        - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      # Only for Kubernetes ^1.7.3.
      # See: https://github.com/prometheus/prometheus/issues/2916
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [ __meta_kubernetes_node_name ]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    metric_relabel_configs:
      - action: replace
        source_labels: [ id ]
        regex: '^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$'
        target_label: rkt_container_name
        replacement: '${2}-${1}'
      - action: replace
        source_labels: [ id ]
        regex: '^/system\.slice/(.+)\.service$'
        target_label: systemd_service_name
        replacement: '${1}'