groups:
  - name: prometheus
    rules:
      - record: code:prometheus_http_requests_total:sum
        expr: sum by (code) (prometheus_http_requests_total)
  - name: messages
    rules:
      - record: code:messages_received_total:sum
        expr: sum by (code) (messages_received_total)