global:
  scrape_interval: 60s
scrape_configs:
  - job_name: 'sender'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['sender:8081']
  - job_name: 'recipient'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'recipient:8082' ]
  - job_name: 'collector'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'collector:8083' ]
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'rabbitmq:15692' ]
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']